import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/shared/layout/layout";
import Hero from "@/components/ui/hero/hero";
import Business from "@/components/ui/business/business";
import ProductsCard from "@/components/ui/productsCard/productsCard";
import Serve from "@/components/ui/serve/serve";
import Service from "@/components/ui/service/service";
import Reviews from "@/components/ui/reviews/reviews";
import GlobalClient from "@/components/ui/globe/globe";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>CortexSof</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div>
          <Hero />
          <Business />
          <ProductsCard />
          <Serve />
          <hr />
          <Service />
          <Reviews />
          <br />
          <GlobalClient />
          <br />
          <br />
          <br />
        </div>
      </Layout>
    </>
  );
}
